<?php
namespace backend\models;

use yii\base\Model;

class User extends Model {

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->on(User::USER_REGISTERED, function($event){
            #var_dump($event->name);   //Название события
            #var_dump($event->sender);   //Модель в который было вызано событие
            #var_dump($event->data);
            var_dump($event->data);
        }, ['tp' => '666']);

        #method 2
        $this->on(User::USER_REGISTERED, [$this, 'someMethod']);

        #method 3
        $this->on(User::USER_REGISTERED, ['backend\models\User2', 'twoMethod']);

        #method 4 (глобальные методы php)
        $this->on(User::USER_REGISTERED, 'get_class');
    }


    const USER_REGISTERED = 'user registered';


    public function someMethod($event){
        var_dump('aaaaaaaaaaaaaaaaaaaaaaa');
        $event->handled = true;
    }

    public function thirdMethod(){
        var_dump('lllllllllllllll');
    }

    public function userRegistered(){
        $this->trigger(User::USER_REGISTERED);
    }

}